### ISSUE TITLE
RoR group project: Set up  Kanban board

### ISSUE THREAD

**Issue by AlierPM** [AlierPM/Recipedaily#15]
**GitHub Project Link:** [[Our Group Project Link ](https://github.com/users/AlierPM/projects/3)]

**Team Size:** [2 members]

---

### Description:

We're excited to kick off our project using GitHub Projects and a Kanban board. As this is our first time utilizing these tools, we want to ensure that our setup is accurate and won't cause any issues during the development process.

**Action Items:**
1. Confirm that the GitHub Project is linked correctly.
2. Verify that the Kanban board reflects our planned tasks and assignments.
3. Check for any potential pitfalls or misconfigurations.

Please use this issue to provide feedback on our GitHub Project and Kanban board setup. Your insights will be crucial in ensuring a smooth development workflow.

Thank you for your assistance!

**Comment by algerina** [comment]
Hello team, 
Well done creating all the cards with description, your Kanban board as approved, you can now start your project.

**Comment by AlierPM** [comment]
Thanks @algerina
